name = "PlaceholderLikelihood"
uuid = "af9eadfc-028e-4dd7-8324-1a9c134c7af2"
authors = ["JoelTrent <79883375+JoelTrent@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
